#Права:
#  fermsubs.admin - доступ к командам в /subs

fly:
  enabled: true
  сoolDowns: 40 #в секундах (как часто игрок сможет включать и выключать флай)
  command: 'fly' #команда, чтобы зайти в GUI
  msg:
    prefix: '&9&lФлай &7>'
    buy: '%prefix% &fУ вас не куплен &9флай&f, купите его на сайте - &e&nFermBuy.Ru'
    enabled: '%prefix% &fВы &aвключили &fрежим полёта.'
    disabled: '%prefix% &fВы &cвыключили &fрежим полёта.'
    cooldown: '%prefix% &fПодождите &e%time% &fсек.'

  GUI:
    headline: 'FermSubs'
    fly:
      id: 288 #ид предмета в GUI
      slot: 11 #позиция в GUI
      name: '&a&nРЕЖИМ ПОЛЁТА'
      lores:
      - '&fУ вас %working% &fрежим полёта.'
    help:
      id: 340 #ид предмета в GUI
      slot: 14 #позиция в GUI
      name: '&a&nКАК КУПИТЬ?'
      lores:
      - '&c1) &fЗайдите на наш сайт - &6FermBuy.Ru'
      - '&7(Нажмите ЛКМ, чтобы получить ссылку)'
      - '&c2) &fВпишите ник и выберите из списка'
      - '&fдоната «&9Флай&f»'
      - '&c3) &fОплатите любым удобным способом.'
      - '&c4) &fПосле оплаты режим полёта придёт'
      - '&fсразу же.'
      - '&c5) &fВключите режим полёта в &l/fly&f и'
      - '&fнаслаждайтесь прекрасными видами сервера.'
      url: '%prefix% &fСсылка на сайт для покупки режима полёта: &e&nFermBuy.Ru&7 (нажмите на ссылку)' #сообщение при нажатии на help
    subs:
      id: 395 #ид предмета в GUI
      slot: 17 #позиция в GUI
      name: '&a&nПОДПИСКА'
      lores:
      - 'Осталось: &e&l%timeSubs%'

god:
  enabled: true
  сoolDowns: 180 #в секундах (как часто игрок сможет включать и выключать режим бога)
  command: 'god' #команда, чтобы зайти в GUI
  msg:
    prefix: '&c&lРежим бога &7>'
    buy: '%prefix% &fУ вас не куплен &cрежим бога&f, купите его на сайте - &e&nFermBuy.Ru'
    enabled: '%prefix% &fВы &aвключили &fрежим бога.'
    disabled: '%prefix% &fВы &cвыключили &fрежим бога.'
    cooldown: '%prefix% &fПодождите &e%time% &fсек.'

  GUI:
    headline: 'FermSubs'
    god:
      id: 311 #ид предмета в GUI
      slot: 11 #позиция в GUI
      name: '&a&nРЕЖИМ БОГА'
      lores:
      - '&fУ вас %working% &fрежим бога.'
    help:
      id: 340 #ид предмета в GUI
      slot: 14 #позиция в GUI
      name: '&a&nКАК КУПИТЬ?'
      lores:
      - '&c1) &fЗайдите на наш сайт - &6FermBuy.Ru'
      - '&7(Нажмите ЛКМ, чтобы получить ссылку)'
      - '&c2) &fВпишите ник и выберите из списка'
      - '&fдоната «&cРежим бога&f»'
      - '&c3) &fОплатите любым удобным способом.'
      - '&c4) &fПосле оплаты режим бога придёт'
      - '&fсразу же.'
      - '&c5) &fВключите режим бога в &l/god&f,'
      - '&fтеперь вас не пробьёт даже топка.'
      url: '%prefix% &fСсылка на сайт для покупки режима бога: &e&nFermBuy.Ru&7 (нажмите на ссылку)' #сообщение при нажатии на help
    subs:
      id: 395 #ид предмета в GUI
      slot: 17 #позиция в GUI
      name: '&a&nПОДПИСКА'
      lores:
      - 'Осталось: &e&l%timeSubs%'

protect:
  enabled: true
#  сoolDowns: 60 #в секундах (как часто игрок сможет включать и выключать режим бога)
  command: 'protect' #команда, чтобы зайти в GUI
  msg:
    prefix: '&c&lЗащита &7>'
    buy: '%prefix% &fУ вас не куплена &6защита от банов, киков, мутов&f, купите её на сайте - &e&nFermBuy.Ru'
#    on: '%prefix% &fВы &aвключили &fзащиту от банов, киков, мутов.'
#    off: '%prefix% &fВы &cвыключили &fзащиту от банов, киков, мутов.'
#    cooldown: '%prefix% &fПодождите &e%time% &fсек.'
    protected: '%player% защищен'

  GUI:
    headline: 'FermSubs'
    protect:
      id: 166 #ид предмета в GUI
      slot: 11 #позиция в GUI
      name: '&a&nЗАЩИТА ОТ БАНОВ, КИКОВ, МУТОВ'
      lores:
      - '&fУ вас %working%а &fзащита.'
      - ''
      - '&7Даже с защитой вы должны соблюдать правила'
      - '&7сервера. В противном случае администрация сервера'
      - '&7сможет заблокировать ваш аккаунт.'
      - '&7Защита создана для спокойной игры, чтобы донатеры'
      - '&7злоупотребляющие командами не могли выдать вам'
      - '&7бан, кик или мут.'
    help:
      id: 340 #ид предмета в GUI
      slot: 14 #позиция в GUI
      name: '&a&nКАК КУПИТЬ?'
      lores:
      - '&c1) &fЗайдите на наш сайт - &6FermBuy.Ru'
      - '&7(Нажмите ЛКМ, чтобы получить ссылку)'
      - '&c2) &fВпишите ник и выберите из списка'
      - '&fдоната «&6Защита&f»'
      - '&c3) &fОплатите любым удобным способом.'
      - '&c4) &fПосле оплаты защита от банов,'
      - '&fкиков, мутов, придёт сразу же.'
      - '&c5) &fВключите защиту в &l/protect&f и'
      - '&fиграйте со спокойной душой.'
      url: '%prefix% &fСсылка на сайт для покупки защиты: &e&nFermBuy.Ru&7 (нажмите на ссылку)' #сообщение при нажатии на help
    subs:
      id: 395 #ид предмета в GUI
      slot: 17 #позиция в GUI
      name: '&a&nПОДПИСКА'
      lores:
      - 'Осталось: &e&l%timeSubs%'

messages:
  prefix: '&6&lПодписки &7>' #префикс для админ-команд
  timeSubsNull: '&cПОДПИСКА ОТСУТСВУЕТ' #Если подписки у игрока нет или она закончилась
  working: #для GUI
    enabled: '&aвключен'
    disabled: '&cвыключен'
  help: #Введя команду /subs
    - '%prefix% &fСписок возможных команд:'
    - '&e/subs add (fly/god/protect) (ник) (время) &7— &fВыдать время подписки игроку.'
    - '&e/subs take (fly/god/protect) (ник) (время) &7— &fЗабрать время подписки у игрока.'
    - '&e/subs reload &7— &fПерезагрузка конфигурации.'
  nameSubs: #названия подписок для сообщений
    fly: '&9флая'
    god: '&cрежима бога'
    protect: '&6защиты'
  add: '%prefix% &fВы добавили %timeSubs% %nameSubs% &fигроку &e%player%&f.'
  take: '%prefix% &fВы забрали %timeSubs% %nameSubs% &fу игрока &e%player%&f.'
  reload: '%prefix% &fКонфигурация перезагружена.'
  notTime: 'pls use format 1y1d1h1m1s, you write %time%'

history:
  format:
    name: '&fКуплена подписка игроком: &e&l%player%'
    lore:
    - '&fПолучен %nameSubs% &fна %timeSubs%&f.'
    - '&fВремя получения: &e%time%'
  prizes:
  - nick;название;00.00.2000;00:00:00
  - nick;название;00.00.2000;00:00:00
  - nick;название;00.00.2000;00:00:00
  - nick;название;00.00.2000;00:00:00
  - nick;название;00.00.2000;00:00:00
  - nick;название;00.00.2000;00:00:00
  - nick;название;00.00.2000;00:00:00
  - nick;название;00.00.2000;00:00:00
  - nick;название;00.00.2000;00:00:00